apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: merge-clusters-and-list
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              values:
                kafka: 'true'
                redis: 'false'
          # For clusters with a specific label, enable Kafka.
          - clusters:
              selector:
                matchLabels:
                  # use-kafka: 'false'
                  staging: "true"
              values:
                kafka: 'false'
          # For a specific cluster, enable Redis.
          - list:
              elements:
                - server: https://172.16.203.52:6443
                  values.redis: 'true'
  template:
    metadata:
      name: '{{.nameNormalized}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/xyang0917/argocd-example-apps/
        targetRevision: HEAD
        path: helm-guestbook
        helm:
          parameters:
            - name: kafka
              value: '{{.values.kafka}}'
            - name: redis
              value: '{{.values.redis}}'
      destination:
        server: '{{.server}}'
        namespace: default
