# This example demonstrates the combining of the git generator with a cluster generator
# The expected output would be an application per git directory and a cluster (application_count = git directory * clusters)
#
#
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/xyang0917/argo-cd.git
            revision: HEAD
            directories:
            - path: applicationset/examples/matrix/cluster-addons/*
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.path.basename}}-{{.nameNormalized}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/xyang0917/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.path.basename}}'
