# This example demonstrates the combining of the git generator with a list generator
# The expected output would be an application per git directory and a list entry (application_count = git directory * list entries)
#
#
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-git
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/xyang0917/argo-cd.git
          revision: HEAD
          directories:
          - path: applicationset/examples/matrix/cluster-addons/*
      - list:
          elements:
          - cluster: engineering-dev
            url: https://172.16.203.51:6443
            values:
              env: dev
          - cluster: engineering-prod
            url: https://172.16.203.52:6443
            values:
              env: prod
  template:
    metadata:
      name: '{{.path.basename}}-{{.cluster}}'
      labels:
        app-env: '{{.values.env}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/xyang0917/argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.path.basename}}'
